function OperationEnums() {
    const Operations = {
        BRANDSELC:1,
        BRANDINSRT:2,
        BRANDUPDT:3,
        BRANDLIST:4,
        BRANDDELT:5,
        CATGRSELC:6,
        CATGRINSRT:7,
        CATGRUPDT:8,
        CATGRLIST:9,
        CATGRDELT:10,
        SBCATSELC:11,
        SBCATINSRT:12,
        SBCATUPDT:13,
        SBCATLIST:14,
        SBCATDELT:15,
        UNITSSELC:16,
        UNITSINSRT:17,
        UNITSUPDT:18,
        UNITSLIST:19,
        UNITSDELT:20,
        PAYMTSELC:21,
        PAYMTINSRT:22,
        PAYMTUPDT:23,
        PAYMTLIST:24,
        PAYMTDELT:25,
        USRSSELC:26,
        USRSINSRT:27,
        USRSUPDT:28,
        USRSLIST:29,
        USRSDELT:30,
        ROLESLIST:31,
        STRESELC:32,
        STREINSRT:33,
        STREUPDT:34,
        STRELIST:35,
        STREDELT:36,
        EXPTPSELC:37,
        EXPTPINSRT:38,
        EXPTPUPDT:39,
        EXPTPLIST:40,
        EXPTPDELT:41,
        TAXTPSELC:42,
        TAXTPINSRT:43,
        TAXTPUPDT:44,
        TAXTPLIST:45,
        TAXTPDELT:46,
        USRSTRSELC:47,
        USRSTRINSR:48,
        USRSTRUPDT:49,
        USRSTRLIST:50,
        USRSTRDELT:51,
        EXPNSSELC:52,
        EXPNSINSRT:53,
        EXPNSUPDT:54,
        EXPNSLIST:55,
        EXPNSDELT:56,
        DISCTSELC:57,
        DISCTINSRT:58,
        DISCTUPDT:59,
        DISCTLIST:60,
        DISCTDELT:61,
        SIGNIN:62,
        VARNTINSRT:64,
        VARNTUPDT: 65,
        VARNTLIST:66,
        DASHBCNT:67,
        USRSTRUSR:68,
        PRODSELC:69,
        DASHTPPD:70,
        STRPRSELC:71,
        SUPLRLIST: 72,
        STKIDLIST:73,
        PURCHREQ:74,
        PURCHORD:75,
        PRBYID: 76,
        POBYID:77,
        PORECEIVEBYID:78,
        DDLSELC: 79,
        RSECURSEL: 80,
        APRVDINDTLIST:81,
        INDENTLIST:82,
        GETREPORTHEAD:83,
        GETSTCKTRFRLIST:84,
        CUSTLIST: 85,
        INDSTUSUPDT: 86,
        ORDERGETS:87,
        COMBODDL:88,
        PRDCMBGET:89,
        STFINSRT:90,
        STFUPDT:91,
        STFGETS:92,
        STFDELT:93,
        SUPRDETAILS:94,
        SUPPDELT: 95,
        POTERMINSRT:96,
        POTERMUPDT:97,
        POTERMGET:98,
        POTERMDELT:99,
        ORDERLIST:100,
        ORDERSELC:101,
        METRTSINSRT:102,
        PENDINGPYMTLIST:103,
        METRTEGETS:104,
        INVOICEGET:105,
        POPAYINSRT:106,
        POPAYGET:107,
        STKTRFRGET:108,
        QUOTGETLIST:109,
        QUOTGETBYID:110,
        PRINTINVOICE:111,
        STORESECUREGET:112,
        GETSTCKLIST: 114,
        PRODCMBV: 115,
        GETCONSIND: 116,
        SUPDETAILS: 117,
        deleteind:118,
        SUPBYEMAIL: 119,
        DELPOPRODUCT:120,
        GETAPRINDTS:121,
        CHANGEPSWRD:122,
        UPLODDOCS:123,
        GETDOCS:124,
        GETNOTIFY:125,
        GETPURSET:126,
        SUPPAYPEND:127,
        SUPPAYVIEW:128,
        GETSUPPOS:130,
        GETSUPPAYS:131,
        SUPPAYSVIEW:132,
        GETLATEINDREQ: 133,
        NEWLATEINDREQ: 134,
        UPDLATEINDREQ: 135,
        GETSUPSTORDATA: 136,
        GETPRODSORGID: 137,
        GETPRODSBYID: 138,
        GETCATITEMS: 139,
        GETBCTYPE: 140,
        PRODADDETAIL: 141,
        STOCKTRFPDF: 142,
        APPBRANDLIST:143,
        APPCATGRLIST:144,
        APPSTRELIST:145,
        APPSIGNIN:146,
        APPDASHBCNT:147,
        APPSUPLRLIST:148,
        APPCUSTLIST:149,
        APPORDERLIST:150,
        GETORDDET:151,
        APPPRODSELC:152,
        GETREFUND:153,
        GETPRODINV: 154,
        GETDELIVCHAL: 155,
    };

    return Operations;
}

module.exports = {
    OperationEnums
};
